import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { HeaderNav } from "./ui/header-nav";

export const metadata: Metadata = {
  title: "리디 RIDI - clonecoding",
  description: "Generated by create next app",
};

const notoSans = Noto_Sans_KR({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="ko">
      <body>
        <div className="header-wrap  border-b">
          <header className="px-8 flex justify-between max-w-[1170px] m-auto">
            <HeaderNav />
            <ul className="flex">
              <li className={`${notoSans.className} p-3 font-bold text-sm text-[#787878] hover:opacity-40`}>
                <Link href="#"><p>로그인</p></Link>
              </li>
              <li className={`${notoSans.className} p-3 font-bold text-sm text-[#787878] hover:opacity-40`}>
                <Link href="#"><p>회원가입</p></Link>
              </li>
            </ul>
          </header>
        </div>
        {children}
      </body>
    </html>
  );
}
